### ISSUE TITLE
Minimal UI for Home Page

### ISSUE THREAD

**Issue by gobbledy-gook** [scosh-svnit/FunkySudoku#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A minimal and good-looking UI for Sudoku Solver. 
- [x] Title
- [x] Company Logo
- [x] Sudoku Grid
- [x] Reset and Solve buttons
- [x] Header and Footer

**Describe alternatives you've considered**

**Additional context**

**Comment by adityak1911** [comment]
please assign this issue to me
